"""init_db

Revision ID: db2822ee4544
Revises: 
Create Date: 2026-09-18 00:59:04.574771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db2822ee4544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID，多租户隔离；默认 default'),
    sa.Column('source', sa.String(length=512), nullable=False, comment='文档来源标识（相对路径或 URI），与 ingest Source 产出一致'),
    sa.Column('title', sa.String(length=512), nullable=True, comment='文档标题（可选，展示用）'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='正文内容哈希；未变则增量入库跳过'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态：active | deleted | failed'),
    sa.Column('acl_json', mysql.JSON(), nullable=True, comment='可见角色列表 JSON，如 ["all","finance"]'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='当前写入索引的切片数'),
    sa.Column('chunk_ids_json', mysql.JSON(), nullable=True, comment='切片 ID 列表 JSON，删除/更新时用于对账清理'),
    sa.Column('sparse_backend', sa.String(length=64), nullable=True, comment='写入时的稀疏后端名，如 elasticsearch'),
    sa.Column('vector_backend', sa.String(length=64), nullable=True, comment='写入时的向量后端名，如 milvus / qdrant'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='最近一次失败原因（status=failed 时）'),
    sa.Column('ingested_at', sa.DateTime(), nullable=True, comment='最近一次成功入库时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='行创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='行更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', name='uk_tenant_source'),
    comment='知识库文档账本',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_kb_doc_hash', 'kb_document', ['content_hash'], unique=False)
    op.create_index('idx_kb_doc_status', 'kb_document', ['tenant_id', 'status'], unique=False)
    op.create_table('kb_ingest_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID，与 kb_document.tenant_id 对应'),
    sa.Column('source', sa.String(length=512), nullable=False, comment='本次作业处理的文档 source'),
    sa.Column('trigger_type', sa.String(length=32), nullable=False, comment='触发方式：manual | schedule | webhook 等'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='动作：add | update | delete | skip 等'),
    sa.Column('from_hash', sa.String(length=64), nullable=True, comment='变更前 content_hash（新增可空）'),
    sa.Column('to_hash', sa.String(length=64), nullable=True, comment='变更后 content_hash（删除可空）'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='作业结果：success | failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='本次写入/删除涉及的切片数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败详情'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='作业开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='作业结束时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='入库任务流水',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_kb_job_source', 'kb_ingest_job', ['tenant_id', 'source', 'started_at'], unique=False)
    op.create_index('idx_kb_job_status', 'kb_ingest_job', ['status', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kb_job_status', table_name='kb_ingest_job')
    op.drop_index('idx_kb_job_source', table_name='kb_ingest_job')
    op.drop_table('kb_ingest_job')
    op.drop_index('idx_kb_doc_status', table_name='kb_document')
    op.drop_index('idx_kb_doc_hash', table_name='kb_document')
    op.drop_table('kb_document')
    # ### end Alembic commands ###
